[package]
name = "cprp-rust-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
serialport = "4.2"
rfd = "0.10"
csv = "1.3"   # if you want to use CSV functionality
rand = "0.8"  # if you want to generate random/test data
