[package]
name = "forward_to_plotjuggler"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.35", features = ["derive"] }
bevy_math = "0.15.3"
crossterm = "0.29.0"
